version: '1.0'
services:
  pg_instance:
    image: postgres:15
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_DB=frt
    volumes:
      - "./_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U pgadmin -d frt'"]
      interval: 10s
      timeout: 3s
      retries: 3
  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "8080:80"
  ingest_script:
    build: ./
    volumes:
      - .:/app/
    links:
      - pg_instance
    depends_on:
      pg_instance:
        condition: service_healthy

